### ISSUE TITLE
Custom account remains logged in after Clef signout

### ISSUE THREAD

**Issue by jxs714** [clef/clef-whmcs#3]
Hey guys,

Another heads up, the customer account stays logged in even when you logout from the Clef mobile app. Tried this a few times and it is definitely an issue with WHMCS.

**Comment by jessepollak** [comment]
Thanks for the heads up — this is an issue we're looking into. So far, I've been able to replicate the error, but not find the root cause. 

In a local environment, everything works perfectly, so it may be that I need to (1) get access to a deployed environment (2) deploy my own environment. Looking into it!

**Comment by blueearthcom** [comment]
Thanks Jesse, 
I shall try the default the template ASAP and see if it's specific to the template currently being used.

**Comment by tabp0le** [comment]
What should the logout hook be?

**Comment by jessepollak** [comment]
It should be the root URL of your site — can you try that and let me know if it works?

**Comment by KhensU** [comment]
Hi,
I was just trying the module out and had the same issue. However if I use <root url>/?m=clef as the logout hook URL, it will work.  The POST variable is cleared otherwise before it gets to the hook for whatever reason.

**Comment by jessepollak** [comment]
Thank you for that update! I'll adjust the README.md accordingly :)
